// <auto-generated />
using System;
using Euphonia.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219130816_AddYouTubeFields")]
    partial class AddYouTubeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Historiek", b =>
                {
                    b.Property<int>("HistoriekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("historiekID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoriekID"));

                    b.Property<DateTime?>("PeriodeEinde")
                        .HasColumnType("datetime2")
                        .HasColumnName("periode_einde");

                    b.Property<DateTime?>("PeriodeStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("periode_start");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("HistoriekID");

                    b.ToTable("historiek");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Muziek", b =>
                {
                    b.Property<int>("MuziekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("muziekID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuziekID"));

                    b.Property<string>("Artiest")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("artiest");

                    b.Property<string>("Bron")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bron");

                    b.Property<string>("Titel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("titel");

                    b.Property<string>("YouTubeThumbnailUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("youtubeThumbnailUrl");

                    b.Property<string>("YouTubeVideoId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("youtubeVideoId");

                    b.HasKey("MuziekID");

                    b.ToTable("muziek");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.MuziekAnalyse", b =>
                {
                    b.Property<int>("AnalyseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("analyseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalyseID"));

                    b.Property<string>("Bron")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bron");

                    b.Property<string>("EnergieLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("energieLevel");

                    b.Property<int?>("MuziekID")
                        .HasColumnType("int")
                        .HasColumnName("muziekID");

                    b.Property<string>("StemmingType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stemmingType");

                    b.Property<string>("Tempo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tempo");

                    b.Property<int?>("Valence")
                        .HasColumnType("int")
                        .HasColumnName("valence");

                    b.HasKey("AnalyseID");

                    b.HasIndex("MuziekID");

                    b.ToTable("muziekAnalyse");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Notificatie", b =>
                {
                    b.Property<int>("NotificatieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notificatieID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificatieID"));

                    b.Property<DateTime?>("DatumTijd")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_tijd");

                    b.Property<string>("Icoon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icoon");

                    b.Property<bool>("IsGelezen")
                        .HasColumnType("bit")
                        .HasColumnName("isGelezen");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("link");

                    b.Property<string>("Tekst")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tekst");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("NotificatieID");

                    b.HasIndex("UserID");

                    b.ToTable("notificatie");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Profiel", b =>
                {
                    b.Property<int>("ProfielID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("profielID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfielID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Stemmingstags")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stemmingstags");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<string>("VoorkeurGenres")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("voorkeur_genres");

                    b.HasKey("ProfielID");

                    b.ToTable("profiel");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Statistiek", b =>
                {
                    b.Property<int>("StatistiekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statistiekID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatistiekID"));

                    b.Property<string>("Resultaat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("resultaat");

                    b.Property<string>("TrendType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trend_type");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("StatistiekID");

                    b.ToTable("statistiek");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Stemming", b =>
                {
                    b.Property<int>("StemmingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stemmingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StemmingID"));

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("beschrijving");

                    b.Property<DateTime?>("DatumTijd")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_tijd");

                    b.Property<int?>("TypeID")
                        .HasColumnType("int")
                        .HasColumnName("typeID");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("StemmingID");

                    b.HasIndex("TypeID");

                    b.ToTable("stemming");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.StemmingMuziek", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<int?>("MuziekID")
                        .HasColumnType("int")
                        .HasColumnName("muziekID");

                    b.Property<int?>("StemmingID")
                        .HasColumnType("int")
                        .HasColumnName("stemmingID");

                    b.HasKey("PK");

                    b.HasIndex("MuziekID");

                    b.HasIndex("StemmingID");

                    b.ToTable("stemmingMuziek");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.StemmingType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("typeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("beschrijving");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("naam");

                    b.HasKey("TypeID");

                    b.ToTable("stemmingType");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("e-mail");

                    b.Property<decimal?>("Rol")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rol");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<string>("WachtwoordHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("wachtwoord");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[e-mail] IS NOT NULL");

                    b.ToTable("table1_user");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.MuziekAnalyse", b =>
                {
                    b.HasOne("Euphonia.DataAccessLayer.Models.Muziek", "Muziek")
                        .WithMany("Analyses")
                        .HasForeignKey("MuziekID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Muziek");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Notificatie", b =>
                {
                    b.HasOne("Euphonia.DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Stemming", b =>
                {
                    b.HasOne("Euphonia.DataAccessLayer.Models.StemmingType", "StemmingType")
                        .WithMany("Stemmingen")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StemmingType");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.StemmingMuziek", b =>
                {
                    b.HasOne("Euphonia.DataAccessLayer.Models.Muziek", "Muziek")
                        .WithMany("StemmingMuzieks")
                        .HasForeignKey("MuziekID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Euphonia.DataAccessLayer.Models.Stemming", "Stemming")
                        .WithMany("StemmingMuzieks")
                        .HasForeignKey("StemmingID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Muziek");

                    b.Navigation("Stemming");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Muziek", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("StemmingMuzieks");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.Stemming", b =>
                {
                    b.Navigation("StemmingMuzieks");
                });

            modelBuilder.Entity("Euphonia.DataAccessLayer.Models.StemmingType", b =>
                {
                    b.Navigation("Stemmingen");
                });
#pragma warning restore 612, 618
        }
    }
}
